include: package:flutter_lints/flutter.yaml
linter:
  rules:
    non_constant_identifier_names: false
    prefer_const_constructors: false
    avoid_unnecessary_containers: false
    lowercase_with_underscores: false
    file_names: false
    const_constructor_with_non_final_field: false
    prefer_const_literals_to_create_immutables: false
