name: flutter_getx_boilerplate
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.0.1
  get: ^4.3.8
  get_storage: ^2.0.3
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+4
  intl: ^0.17.0
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
